name: Deploy to the gh-pages branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          # creates a .nojekyll file in the out directory to tell GitHub Pages not to treat the site as a Jekyll project.
          touch out/.nojekyll

      - name: Deploy to the gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out
